### ISSUE TITLE
October 2015 

### ISSUE THREAD

**Issue by meaku** [nodeschool/augsburg#1]
We are planning a nodeschool @peerigon in November. The event will be public and we will invite our students from the university of applied sciences. 

@alexlawrence maybe your students will be interested as well? There are some workshoppers targeting js and not only node.js specific stuff.

**Comment by alexlawrence** [comment]
@meaku Maybe. Tell me the dates and a brief agenda and I can inform my students. However they will take an exam at the beginning of November.

**Comment by meaku** [comment]
@alexlawrence: https://ti.to/nodeschool-augsburg/nodeschool-augsburg-oktober-2015 

We want to organize nodeschool events every 2 months. So maybe next time will be better for your students.

**Comment by alexlawrence** [comment]
:+1:

**Comment by machucarro** [comment]
Hi @meaku! I'm already signed in! But I was thinking that if it will be an introductory course with some node basics perhaps I may be more useful giving you a hand to organise it, what do you think? If you come up with something I may help with just say! :)

**Comment by meaku** [comment]
Thanks @machucarro for your offer to help us! 

There are various workshops participants can choose from: http://nodeschool.io/#workshoppers
So you can choose a workshops that challenges you. 

We are 4 mentors at the moment, which should be fine for 15 nodeschool visitors. But it's the first time and we don't know the skill-level to expect from the visitors. Maybe you could help us mentoring. Is it ok for you to decide spontaneous depending on the skill-level?

**Comment by machucarro** [comment]
Sure! Let's do it like that. if on site you see you need a hand, just tell me! As you saw I'm not that bad improvising ;)

**Comment by meaku** [comment]
Hehe. Thanks! I think you are an expert when it comes to improvising :+1:

**Comment by machucarro** [comment]
oh, you made me blush man! thanks for the compliment! :)
