### ISSUE TITLE
Slack / Discord channel for NodeSchool?

### ISSUE THREAD

**Issue by tobiastimm** [nodeschool/augsburg#9]
Would it make sense to add a slack / discord channel for NodeSchool Munich & Aux? I know many people already have several workspaces, but it would also be easier for people and mentors to collaborate with each other before or after an event.

**Comment by irenama** [comment]
☑️ [nodeschoolauxmuc.slack.com](https://nodeschoolauxmuc.slack.com/) whoopwhoop!

now we just have to advertise it a bit and keep bots and haters out 🤝😃
